package com.microservice.SAPUserService.model;

import jakarta.persistence.*;
import lombok.Data;

/*
 * This is the model class for the users table in the database.
 * It has the following fields:
 * - userId: the id of the user which will generated by the database
 * - fullname: the full name of the user
 * - email: the email of the user which will be unique
 * - password: the password of the user which will be hashed
 * - bio: the bio of the user which will be optional
*/

@Entity
@Table(name = "users")
@Data
public class Users {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "user_id")
    private Long userId;

    @Column(name = "fullname")
    private String fullname;

    @Column(name = "email", unique = true)
    private String email;

    @Column(name = "password")
    private String password;

    @Column(name = "bio")
    private String bio;
}